config/routes.rb
Rails.application.routes.draw do
  get 'users/new'
  root 'welcome#home'
  get 'about', to: 'welcome#about'
  get 'signup', to: 'users#new'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  resources :users, except: [:new]
  resources :articles do
    resources :comments
    resources :likes
  end
  resources :categories, except: [:destroy]
  
end

app/models/article.rb
class Article < ApplicationRecord
  has_many :likes, dependent: :destroy
  has_many :comments
  has_many :article_categories
  has_many :categories, through: :article_categories
  belongs_to :user
  validates :title, presence: {message: 'Specify a name, please'}, length: {in: 5..40}, uniqueness: true
  validates :description, presence: true, length: {minimum:10, too_short: 'too short. Try giving more details!'}
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]
  before_action :require_user, except: [:show, :index]
  before_action :require_same_user, only: [:edit, :update, :destroy]

  def show
    
  end

  def index
    @articles = Article.paginate(page: params[:page], per_page: 4)
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)
    @article.user = current_user
    if @article.save
      flash[:notice] = "Article was created successfully!"
      redirect_to article_path(@article)
    else
      render 'new'
    end
  end

  def edit
   
  end

  def update
    if @article.update(article_params)
      flash[:notice] = "Article was update successfully!"
      redirect_to article_path(@article)
    else
      render 'edit'
    end
  end

  def destroy
    @article.destroy
    redirect_to articles_path
  end

  private

  def set_article
    @article = Article.find(params[:id])
  end

  def article_params
    params.require(:article).permit(:title, :description, category_ids: [])
  end

  def require_same_user
    if current_user != @article.user && !current_user.admin?
      flash[:danger] = 'You can only edit or delete your own article'
      redirect_to @article
    end
  end

end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_form.html.erb
<%= render 'shared/errors', obj: @article %>
<%= form_with(model: @article, local: true ) do |f| %>
<div class="ui form">
  <div class="field">
    <label><%= f.label :title %></label>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <label><%= f.label :description %></label>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <label><%= f.label :category %></label>
    <%= f.collection_select(:category_ids, Category.all, :id, :name,
    { prompt: 'None'}, { multiple: true, size: 5} ) %>
  </div>
  <%= f.submit(@article.new_record? ? 'Post it' : 'Update post', :class => 'ui submit button large fluid') %>
</div>
<% end %>

app/views/articles/edit.html.erb
<div class="contentt spacing-top">
  <h1>Editing article</h1>
  <%= render 'articles/form' %>
  <%= link_to 'Back', articles_path %>
<div class="contentt spacing-top">

app/views/articles/index.html.erb
<div class="container">
  <div class="ui center aligned segment">
    <h1>Articles Listing</h1>
  </div>
  <div class="flickr_pagination">
    <%= will_paginate @articles, :container => false %>
  </div>
  <% @articles.each do |article| %>
  <div class="contentt">
    <div class="ui cards stackable centered">
      <div class="card fluid ui spacing-between">
        <div class="content center aligned">
          <%= link_to article_path(article.id) do %>
            <div class="header"><h1><%= article.title %></h1></div>
          <% end %>
          <div class="meta"><h5><%= article.created_at.strftime("%d/%m/%Y") %></h5></div>
          <div class="description" style="word-wrap: break-word; flex: inherit"><p class="article-content"><%= truncate(article.description, length: 300 ) %></p></div>
          <div class="meta">
          <% if article.user %>
            <p class="grey">by <%= link_to article.user.username, user_path(article.user)  %></p>
          <% end %>
          <div class="ui labeled button" tabindex="0">
            <%= link_to article_likes_path(article), method: :post do %>
              <div class="ui red tiny button">
                <i class="heart icon"></i>
              </div>
            <% end %>
            <a class="ui basic red left pointing label">
              <%= article.likes.count %>
            </a>
          </div>
          <% if article.categories.any? %>
            <%= render article.categories %>
          <% end %>
          </div>
          <%= link_to 'READ', article_path(article.id), class: 'tiny ui button spacing-top violet' %>
          <% if logged_in? && (article.user == current_user || current_user.admin?) %>
            <%= link_to 'EDIT', edit_article_path(article.id), class: 'tiny ui button spacing-top grey' %>
            <%= link_to 'DELETE', article_path(article.id), method: :delete, data: {confirm: 'Are you sure?'}, class: 'tiny ui button spacing-top red' %>
          <% end %>
        </div>
      </div>
  <% end %>
    </div>
  </div>
  <div class="flickr_pagination">
    <%= will_paginate @articles, :container => false %>
  </div>
</div>
  

app/views/articles/new.html.erb
<div class="contentt spacing-top">
  <h1>Creating a new Article</h1>
  <%= render 'articles/form' %>
  <%= link_to 'Back', articles_path %>
</div>

app/views/articles/show.html.erb
<div class="contentt container spacing-top">
  <div class="ui cards stackable centered">
    <div class="card fluid ui">
      <div class="content center aligned">
        <%= link_to gravatar_for(@article.user, size: 100), user_path(@article.user) %>
        <div class="meta"><p> by <%= link_to @article.user.username %></p></div>
        
        <div class="meta"><h5><%= @article.created_at.strftime("%d/%m/%Y")%></h5></div>
        <div class="header"><h1><%= @article.title %></h1></div>
        <div class="description" style="word-wrap: break-word; flex: inherit" ><p class="article-content"><%= @article.description %></p></div>
        <div class="content">
        <% if @article.categories.any? %>
          <%= render @article.categories %>
        <% end %>
        </div>
        <% if logged_in? && (@article.user == current_user || current_user.admin?) %>
          <%= link_to 'Edit', edit_article_path(@article.id), class: 'tiny ui button spacing-top grey' %>
          <%= link_to 'Delete', article_path(@article.id), method: :delete, data: {confirm: 'Are you sure?'}, class: 'tiny ui button spacing-top red' %>
        <% end %>
      </div>
    </div>
  </div>
  <div class="ui labeled button" tabindex="0">
    <% if logged_in? %>
      <% pre_like = @article.likes.find { |like| like.user_id == current_user.id } %>
    <% end %>
    
    <% if pre_like %>
      <%= link_to article_like_path(@article, pre_like), method: :delete do %>
        <div class="ui red button">
          <i class="heart icon"></i> Unlike
        </div>
      <% end %>
    <% else %>
      <%= link_to article_likes_path(@article), method: :post do %>
        <div class="ui red button">
          <i class="heart icon"></i> Like
        </div>
      <% end %>
    <% end %>
    <a class="ui basic red left pointing label">
      <%= @article.likes.count %>
    </a>
  </div>
  <div class="ui comments">
    <h3 class="ui dividing header"><%= pluralize(@article.comments.count, 'comment') %></h3>
    <%= render @article.comments %>
  </div>
  <h3>Leave a reply</h3>
  <% if logged_in? %>
    <%= render 'comments/form' %>
  <% else %>
    <h4>You must be loggin in order to comment</h4>
  <% end %>
</div>

</div>