config/routes.rb
Rails.application.routes.draw do
  get 'users/new'
  root 'welcome#home'
  get 'about', to: 'welcome#about'
  get 'signup', to: 'users#new'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  resources :users, except: [:new]
  resources :articles do
    resources :comments
    resources :likes
  end
  resources :categories, except: [:destroy]
  
end

app/models/user.rb
class User < ApplicationRecord
  before_save {self.email = email.downcase}
  has_secure_password
  has_many :likes, dependent: :destroy
  has_many :comments
  has_many :articles, dependent: :destroy
  validates :username, presence: true, length: {minimun: 3, maximum: 20}, uniqueness: true
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: {maximum: 100}, format: {with: VALID_EMAIL_REGEX}
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :require_user, only: [:edit, :update]
  before_action :require_same_user, only: [:edit, :update, :destroy]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:notice] = "Welecome to the Alpha BLog, #{@user.username}"
      redirect_to articles_path
    else
      render 'new'
    end
  end

  def edit

  end

  def update
    if @user.update(user_params)
      flash[:notice] = "User was update successfully!"
      redirect_to user_path
    else
      render 'edit'
    end
  end

  def show
    @user = set_user
    @articles = @user.articles.paginate(page: params[:page], per_page: 4)
    @likes = count_articles_likes(@user)
    @comments = count_articles_comments(@user)
  end

  def index
    @users = User.paginate(page: params[:page], per_page: 4)
  end

  def destroy
    @user.destroy
    session[:user_id] = nil if @user == current_user
    flash[:notice] = 'Account and articles succesfully deleted'
    redirect_to root_path
  end

  private

  def user_params
    params.require(:user).permit(:username, :email, :password)
  end

  def set_user
    @user = User.find(params[:id])
  end

  def require_same_user
    if current_user != @user && !current_user.admin?
      flash[:alert] = 'You can only edit or delete your own profile'
      redirect_to @user
    end
  end

  def count_articles_likes(user)
    user_articles = user.articles
    count_likes=0
    user_articles.each do |article|
      count_likes = count_likes + article.likes.count
    end
    @likes = count_likes
  end

  def count_articles_comments(user)
    user_articles = user.articles
    count_comments = 0
    user_articles.each do |article|
      count_comments = count_comments + article.comments.count
    end
    @comments = count_comments
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<div class="contentt">
  <%= render 'shared/errors', obj: @user %>
  <%= form_for(@user, :html=> {role: 'form'}) do |f| %>

  <div class="ui form">
    <div class="field">
      <label><%= f.label :username %></label>
      <%= f.text_field :username %>
    </div>
    <div class="field">
      <label><%= f.label :email %></label>
      <%= f.text_field :email %>
    </div>
    <div class="field">
      <%= f.label :password %>
      <%= f.password_field :password %>
    </div>
    <%= f.submit(@user.new_record? ? 'Sign Up' : 'Update Account', :class => 'ui submit button large fluid') %>
  </div>
  <% end %>
</div>

app/views/users/edit.html.erb
<div class="container">
  <div class="ui center aligned segment">
    <h1>Edit Profile</h1>
  </div>
<%= render 'users/form' %>
</div>

app/views/users/index.html.erb
<div class="container">
  <div class="ui center aligned segment">
    <h1>Users Listing</h1>
  </div>
  <div class="flickr_pagination">
    <%= will_paginate @users, :container => false %>
  </div>
  <% @users.each do |user| %>
  <div class="contentt">
    <div class="ui cards stackable centered">
      <div class="card fluid ui spacing-between">
        <div class="content center aligned">
          <%= link_to user_path(user.id) do %>
            <div class="header"><h1><%= user.username %></h1></div>
          <% end %>
          <div class="meta"><h5>Joined <%= user.created_at.strftime("%d/%m/%Y") %></h5></div>
          <%= link_to gravatar_for(user, size: 100), user %>
          <div class="meta"><h5><%= pluralize(user.articles.count, 'article') %></h5></div>
          <% if logged_in? %>
            <% if user == current_user %>
              <%= link_to 'EDIT', edit_user_path(user.id), class: 'tiny ui button spacing-top grey' %>
            <% end %>
            <% if current_user.admin? %>
              <%= link_to 'Delete user', user_path(user), class: 'tiny ui button spacing-top red', method: :delete, data: {confirm: 'Are you sure?'} %>
            <% end %>
          <% end %>
        </div>
      </div>
  <% end %>
    <div class="flickr_pagination">
    <%= will_paginate @users, :container => false %>
  </div>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<div class="container">
  <div class="ui center aligned segment">
    <h1>Sign Up</h1>
  </div>
<%= render 'users/form' %>

app/views/users/show.html.erb
<div class="container">
  <div class="ui center aligned segment">
    <% if logged_in? %>
      <h1><%= '(Admin)' if current_user.admin? %><%= @user.username %>'s profile</h1>
    <% end %>
    <%= gravatar_for @user, size: 130 %>
    <% if logged_in? && @user == current_user %>
      <%= link_to 'Update Profile', edit_user_path(@user), class: 'tiny ui button spacing-top grey' %>
      <%= link_to 'Delete Account', user_path(@user), method: :delete, class: 'tiny ui button spacing-top red', data: {confirm: 'Are you sure?'} %>
    <% end %>
  </div>
  

<div class="ui horizontal stripe quote clearing segment">
  <div class="ui equal width internally celled grid">
    <div class="center aligned row">
      <div class="column">
        <h3 class="ui horizontal header divider">
          <%= @user.username %>'s articles has a total of
        </h3>
        <div class="ui statistic">
          <div class="value">
            <i class="comments icon" style="margin-right: 15px;"></i><%= @comments %>
          </div>
          <div class="label">
            Comments
          </div>
          <div class="value">
            <i class="heart icon"style="margin-right: 15px;"></i><%= @likes %>
          </div>
          <div class="label">
            Likes
          </div>
        </div>
      </div>
    </div>
  </div>
</div>


  <div class="flickr_pagination">
    <%= will_paginate @articles, :container => false %>
  </div>

  <div class="ui center aligned segment">
    <div class="contentt">
      <h2>Articles</h2>
      <% @articles.each do |article| %>
      <div class="ui cards stackable centered">
        <div class="card fluid ui spacing-between">
          <div class="content center aligned">
            <%= link_to article_path(article.id) do %>
              <div class="header"><h1><%= article.title %></h1></div>
            <% end %>
            <div class="meta"><h5><%= article.created_at.strftime("%d/%m/%Y") %></h5></div>
            <div class="description"><p class="article-content"><%= truncate(article.description, length: 300 ) %></p>
            <% if article.categories.any? %>
              <%= render article.categories %>
            <% end %>
            </div>
            <%= link_to 'READ', article_path(article.id), class: 'tiny ui button spacing-top violet' %>
            <% if logged_in? && (article.user == current_user || current_user.admin?) %>
              <%= link_to 'EDIT', edit_article_path(article.id), class: 'tiny ui button spacing-top grey' %>
              <%= link_to 'DELETE', article_path(article.id), method: :delete, data: {confirm: 'Are you sure?'}, class: 'tiny ui button spacing-top red' %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
  <% end %>
</div>