config/routes.rb
Rails.application.routes.draw do
  get 'users/new'
  root 'welcome#home'
  get 'about', to: 'welcome#about'
  get 'signup', to: 'users#new'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  resources :users, except: [:new]
  resources :articles do
    resources :comments
    resources :likes
  end
  resources :categories, except: [:destroy]
  
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :article_categories
  has_many :articles, through: :article_categories
  validates :name, presence: true, length: {minimum: 3, maximum: 20}
  validates_uniqueness_of :name
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  
  before_action :require_admin, except: [:index, :show]

  def index
    @categories = Category.paginate(page: params[:page], per_page: 4)
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      flash[:notice] = 'Category was succesfully created!'
      redirect_to @category
    else
      render 'new'
    end
  end
  
  def new
    @category = Category.new
  end

  def show
    @category = Category.find(params[:id])
    @articles = @category.articles.paginate(page: params[:page], per_page: 5)
  end

  def edit
    @category = Category.find(params[:id])
  end

  def update
    @category = Category.find(params[:id])
    if @category.update(category_params)
      flash[:notice] = "Category name updated succesfully"
      redirect_to @category
    else
      render 'edit'
    end
  end

  private

  def category_params
    params.require(:category).permit(:name)
  end

  def require_admin
    if !(logged_in? && current_user.admin?)
      flash[:alert] = 'Only admins can perform this action'
      redirect_to categories_path
    end
  end

end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_category.html.erb
<%= link_to category.name, category_path(category), class: "ui label blue" %>

app/views/categories/create.html.erb
<h1>Categories#create</h1>
<p>Find me in app/views/categories/create.html.erb</p>

app/views/categories/edit.html.erb
<div class="container">
  <div class="ui center aligned segment">
    <h1>Edit Category</h1>
  </div>
  <div class="contentt">
  <%= render 'shared/errors', obj: @category %>
    <%= form_with(model: @category, local: true) do |f| %>
    <div class="ui form">
      <div class="field">
        <label><%= f.label :name, 'Category name' %></label>
        <%= f.text_field :name %>
      </div>
      <%= f.submit 'create category', :class => 'ui submit button large fluid' %>
    </div>
    <% end %>
  </div>
</div>

app/views/categories/index.html.erb
<div class="container">
  <div class="ui center aligned segment">
    <h1>Categories</h1>
  </div>
  <div class="flickr_pagination">
    <%= will_paginate @categories, :container => false %>
  </div>
  <% @categories.each do |category| %>
  <div class="contentt">
    <div class="ui cards stackable centered">
      <div class="card fluid ui spacing-between">
        <div class="content center aligned">
          <%= link_to category_path(category.id) do %>
            <div class="header"><h1><%= category.name %></h1></div>
<div class="meta"><h3><%= pluralize(category.articles.count, 'article') %></h3></div>
          <% end %>
        </div>
      </div>
  <% end %>
  <div class="flickr_pagination">
    <%= will_paginate @categories, :container => false %>
  </div>
    </div>
  </div>
</div>

app/views/categories/new.html.erb
<div class="container">
  <div class="ui center aligned segment">
    <h1>Create a new Category</h1>
  </div>
  <div class="contentt">
  <%= render 'shared/errors', obj: @category %>
    <%= form_with(model: @category, local: true) do |f| %>
    <div class="ui form">
      <div class="field">
        <label><%= f.label :name, 'Category name' %></label>
        <%= f.text_field :name %>
      </div>
      <%= f.submit 'create category', :class => 'ui submit button large fluid' %>
    </div>
    <% end %>
  </div>
</div>

app/views/categories/show.html.erb
<div class="container">
  <div class="ui center aligned segment">
    <h1>Category: <%= @category.name %></h1>
  <% if logged_in? && current_user.admin? %>
    <%= link_to 'Edit', edit_category_path(@category) %>
  <% end %>
  </div>
</div>
<div class="ui center aligned segment">
    <div class="contentt">
      <h2>Articles</h2>
      <% @articles.each do |article| %>
      <div class="ui cards stackable centered">
        <div class="card fluid ui spacing-between">
          <div class="content center aligned">
            <%= link_to article_path(article.id) do %>
              <div class="header"><h1><%= article.title %></h1></div>
            <% end %>
            <div class="meta"><h5><%= article.created_at.strftime("%d/%m/%Y") %></h5></div>
            <div class="description"><p class="article-content"><%= truncate(article.description, length: 300 ) %></p>
            <% if article.categories.any? %>
              <%= render article.categories %>
            <% end %>
            </div>
            <%= link_to 'READ', article_path(article.id), class: 'tiny ui button spacing-top violet' %>
            <% if logged_in? && (article.user == current_user || current_user.admin?) %>
              <%= link_to 'EDIT', edit_article_path(article.id), class: 'tiny ui button spacing-top grey' %>
              <%= link_to 'DELETE', article_path(article.id), method: :delete, data: {confirm: 'Are you sure?'}, class: 'tiny ui button spacing-top red' %>
            <% end %>
          </div>
        </div>
      </div>
      <% end %>
    </div>
  </div>