config/routes.rb
Rails.application.routes.draw do
  get 'users/new'
  root 'welcome#home'
  get 'about', to: 'welcome#about'
  get 'signup', to: 'users#new'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  resources :users, except: [:new]
  resources :articles do
    resources :comments
    resources :likes
  end
  resources :categories, except: [:destroy]
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  has_many :likes, dependent: :destroy
  has_many :comments
  has_many :article_categories
  has_many :categories, through: :article_categories
  belongs_to :user
  validates :title, presence: {message: 'Specify a name, please'}, length: {in: 5..40}, uniqueness: true
  validates :description, presence: true, length: {minimum:10, too_short: 'too short. Try giving more details!'}
end

app/models/article_category.rb
class ArticleCategory < ApplicationRecord
  belongs_to :article
  belongs_to :category
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :article_categories
  has_many :articles, through: :article_categories
  validates :name, presence: true, length: {minimum: 3, maximum: 20}
  validates_uniqueness_of :name
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates :comment, presence: {message: "Can't be blank"}, length: {in: 1..400}
  belongs_to :article
  belongs_to :user
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :article
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  before_save {self.email = email.downcase}
  has_secure_password
  has_many :likes, dependent: :destroy
  has_many :comments
  has_many :articles, dependent: :destroy
  validates :username, presence: true, length: {minimun: 3, maximum: 20}, uniqueness: true
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: {maximum: 100}, format: {with: VALID_EMAIL_REGEX}
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]
  before_action :require_user, except: [:show, :index]
  before_action :require_same_user, only: [:edit, :update, :destroy]

  def show
    
  end

  def index
    @articles = Article.paginate(page: params[:page], per_page: 4)
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)
    @article.user = current_user
    if @article.save
      flash[:notice] = "Article was created successfully!"
      redirect_to article_path(@article)
    else
      render 'new'
    end
  end

  def edit
   
  end

  def update
    if @article.update(article_params)
      flash[:notice] = "Article was update successfully!"
      redirect_to article_path(@article)
    else
      render 'edit'
    end
  end

  def destroy
    @article.destroy
    redirect_to articles_path
  end

  private

  def set_article
    @article = Article.find(params[:id])
  end

  def article_params
    params.require(:article).permit(:title, :description, category_ids: [])
  end

  def require_same_user
    if current_user != @article.user && !current_user.admin?
      flash[:danger] = 'You can only edit or delete your own article'
      redirect_to @article
    end
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :require_user
  def create
    @article = Article.find(params[:article_id])
    @comment = @article.comments.create(params[:comment].permit(:name, :comment))
    @comment.user = current_user
    if @comment.save
      flash[:notice] = "Comment posted successfully!"
      redirect_to article_path(@article)
    else
      flash.now[:notice] = 'Error while sending message!'
    end
  end

  def destroy
    @article= Article.find(params[:article_id])
    @comment = @article.comments.find(params[:id])
    @comment.destroy
    redirect_to article_path(@article)
  end

end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :find_article
  before_action :find_like, only: [:destroy]
  before_action :require_user
  def create
    if already_liked?
      flash[:notice] = "You can't like more than once"
    else
      @article.likes.create(user_id: current_user.id)
    end
    redirect_to article_path(@article)
  end

  def destroy
    if !(already_liked?)
      flash[:notice] = "Cannont unlike"
    else
      @like.destroy
    end
    redirect_to article_path(@article)
  end

  private

  def find_article
    @article = Article.find(params[:article_id])
  end

  def already_liked?
    Like.where(user_id: current_user.id, article_id: params[:article_id]).exists?
  end

  def find_like
    @like = @article.likes.find(params[:id])
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :require_user, only: [:edit, :update]
  before_action :require_same_user, only: [:edit, :update, :destroy]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:notice] = "Welecome to the Alpha BLog, #{@user.username}"
      redirect_to articles_path
    else
      render 'new'
    end
  end

  def edit

  end

  def update
    if @user.update(user_params)
      flash[:notice] = "User was update successfully!"
      redirect_to user_path
    else
      render 'edit'
    end
  end

  def show
    @user = set_user
    @articles = @user.articles.paginate(page: params[:page], per_page: 4)
    @likes = count_articles_likes(@user)
    @comments = count_articles_comments(@user)
  end

  def index
    @users = User.paginate(page: params[:page], per_page: 4)
  end

  def destroy
    @user.destroy
    session[:user_id] = nil if @user == current_user
    flash[:notice] = 'Account and articles succesfully deleted'
    redirect_to root_path
  end

  private

  def user_params
    params.require(:user).permit(:username, :email, :password)
  end

  def set_user
    @user = User.find(params[:id])
  end

  def require_same_user
    if current_user != @user && !current_user.admin?
      flash[:alert] = 'You can only edit or delete your own profile'
      redirect_to @user
    end
  end

  def count_articles_likes(user)
    user_articles = user.articles
    count_likes=0
    user_articles.each do |article|
      count_likes = count_likes + article.likes.count
    end
    @likes = count_likes
  end

  def count_articles_comments(user)
    user_articles = user.articles
    count_comments = 0
    user_articles.each do |article|
      count_comments = count_comments + article.comments.count
    end
    @comments = count_comments
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def home
    @article_most_liked = find_most_liked_article
    @article_most_commented = find_most_commented_article
    @recents_articles = find_recents_articles
  end

  def about

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def gravatar_for(user, options = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.username, class: 'ui image circular centered')
  end
  


end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/_footer.html.erb
<div class="spacing-footer">
<div class="ui inverted vertical footer segment">
  <div class="ui container">
    <div class="ui centered segment stackable inverted divided equal height stackable grid">
      <div class="three wide column">
        <h4 class="ui inverted header">About</h4>
          <div class="ui inverted link list">
            <a class="item" href="#">Lorem Ipsum</a>
            <a class="item" href="#">Lorem Ipsum</a>
            <a class="item" href="#">Lorem Ipsum</a>
          </div>
      </div>
      <div class="three wide column">
        <h4 class="ui inverted header">Lorem Ipsum</h4>
          <div class="ui inverted link list">
            <a class="item" href="#">Lorem Ipsum</a>
            <a class="item" href="#">Lorem Ipsum</a>
            <a class="item" href="#">Lorem Ipsum</a>
          </div>
      </div>
      <div class="three wide column">
        <h4 class="ui inverted header">Lorem Ipsum</h4>
          <div class="ui inverted link list">
            <a class="item" href="#">Lorem Ipsum</a>
            <a class="item" href="#">Lorem Ipsum</a>
            <a class="item" href="#">Lorem Ipsum</a>
          </div>
      </div>
    </div>
  </div>
</div>
</div>

app/views/layouts/_messages.html.erb
  <% flash.each do |name, msg| %>
    <div class="ui positive message spacing-top">
      <p><%= msg %></p>
    </div>
  <% end %>

app/views/layouts/_navigation.html.erb
<div class="navbar-bg">
  <div class="navbar white">
    <div class="ui text menu large navbar secondary">
      <a class="brand item">
        <div class="content">
          <%= link_to 'ALPHA BLOG', root_path, class: 'ui header white large' %>
        </div>
      </a>
      <%= link_to 'Home', root_path, class: 'active item white navbar-links stroke-effect spacing-left spacing-top' %>
      <%= link_to 'About', about_path, class: 'item white navbar-links spacing-top' %>
      <div class="ui simple dropdown item white navbar-links spacing-top">
        Articles
        <i class="dropdown icon"></i>
        <div class="menu">
          <% if logged_in? %>
            <%= link_to 'Create Article', new_article_path, class: 'item white navbar-links spacing-top' %>
          <% end %>
          <div class="item white navbar-links"><%= link_to 'Listing', articles_path %></div>
        </div>
      </div>
      <div class="ui simple dropdown item white navbar-links spacing-top">
        Categories
        <i class="dropdown icon"></i>
        <div class="menu">
          <% if logged_in? && current_user.admin? %>
            <%= link_to 'Create Category', new_category_path, class: 'item white navbar-links spacing-top' %>
          <% end %>
          <div class="item white navbar-links"><%= link_to 'Listing', categories_path %></div>
        </div>
      </div>
      <%= link_to 'Users', users_path, class: 'item white navbar-links spacing-top' %>
      <div class="right menu">
        <% if logged_in? %>
          <%= link_to user_path(current_user), class: 'ui item white' do %>
            <button class="ui inverted button">Profile</button>
          <% end %>
          <%= link_to logout_path, class: 'ui item white', method: :delete do %>
            <button class="ui inverted button">Log Out</button>
          <% end %>
        <% else %>
          <%= link_to signup_path, class: 'ui item white' do %>
            <button class="ui inverted button">Sign Up</button>
          <% end %>
          <%= link_to login_path, class: 'ui item white' do %>
            <button class="ui inverted button">Sign In</button>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AlphaBlog514</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navigation' %>
    
    <div class="contentt">
      <%= render 'layouts/messages' %>
    </div>
    <%= yield %>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
  <div class="ui negative message">
    <i class="exclamation circle"></i>
    <div class="header">
      <h3>The following errors prevented the <%= obj.class.name.downcase %> from being saved</h3>
    </div>
    <ul class="list">
      <% obj.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>